[package]
name = "abp-runtime"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
abp-core = { path = "../abp-core" }
abp-integrations = { path = "../abp-integrations" }
abp-policy = { path = "../abp-policy" }
abp-workspace = { path = "../abp-workspace" }
anyhow.workspace = true
chrono.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tracing.workspace = true
uuid.workspace = true
