[package]
name = "abp-host"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
abp-core = { path = "../abp-core" }
abp-protocol = { path = "../abp-protocol" }
sidecar-kit = { path = "../sidecar-kit" }
anyhow.workspace = true
thiserror.workspace = true
futures.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tracing.workspace = true
