[package]
name = "abp-integrations"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
abp-backend = { path = "../abp-backend" }
abp-backend-mock = { path = "../abp-backend-mock" }
abp-backend-sidecar = { path = "../abp-backend-sidecar" }
