[package]
name = "abp-integrations"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
abp-backend = { path = "../abp-backend" }
abp-mock-backend = { path = "../abp-mock-backend" }
abp-sidecar-backend = { path = "../abp-sidecar-backend" }
