[package]
name = "abp-integrations"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
abp-core = { path = "../abp-core" }
abp-host = { path = "../abp-host" }
anyhow.workspace = true
async-trait.workspace = true
chrono.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tracing.workspace = true
uuid.workspace = true
