[package]
name = "abp-policy"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
abp-core = { path = "../abp-core" }
anyhow.workspace = true
globset.workspace = true
serde.workspace = true
schemars.workspace = true
